/**
 * @author Calvin Galbaw
 */

export const ADD_PRODUCTTO_CART = "ADD_PRODUCTTO_CART";
export const ADD_QUANTITY_CART = "ADD_QUANTITY_CART";
export const REMOVE_QUANTITY_CART = "REMOVE_QUANTITY_CART";
export const REMOVE_PRODUCTFROM_CART = "REMOVE_PRODUCTFROM_CART";
export const CART_DETAILS_GET = "CART_DETAILS_GET";
export const CART_DETAILS_SUCCESS = "CART_DETAILS_SUCCESS";
export const CART_DETAILS_ERROR = "CART_DETAILS_ERROR";
export const CART_DETAILS_UPDATE = "CART_DETAILS_UPDATE";
export const CART_DETAILS_UPDATE_SUCCESS = "CART_DETAILS_UPDATE_SUCCESS";
export const CART_DETAILS_UPDATE_ERROR = "CART_DETAILS_UPDATE_ERROR";
export const CART_DETAILS_DELETE = "CART_DETAILS_UPDATE";
export const CART_DETAILS_DELETE_SUCCESS = "CART_DETAILS_UPDATE_SUCCESS";
export const CART_DETAILS_DELETE_ERROR = "CART_DETAILS_UPDATE_ERROR";
export const RESTORE_CART = "RESTORE_CART";
export const LOGOUT_CART = "LOGOUT_CART";
