export const CATEGORY_ALLCATEGORY_GET = "CATEGORY_ALLCATEGORY_GET";
export const CATEGORY_ALLCATEGORY_SUCCESS = "CATEGORY_ALLCATEGORY_SUCCESS";
export const CATEGORY_ALLCATEGORY_ERROR = "CATEGORY_ALLCATEGORY_ERROR";
