/**
 * @author Calvin Galbaw
 */

export const USER_LOGIN_POST = "USER_LOGIN_POST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAILURE = "USER_LOGIN_FAILURE";
export const USER_REGISTER_POST = "USER_REGISTER_POST";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAILURE = "USER_REGISTER_FAILURE";
export const USER_FORGOTPASSWORD_POST = "USER_FORGOTPASSWORD_POST";
export const USER_FORGOTPASSWORD_SUCCESS = "USER_FORGOTPASSWORD_SUCCESS";
export const USER_FORGOTPASSWORD_FAILURE = "USER_FORGOTPASSWORD_FAILURE";
export const USER_RECOVERPASSWORD_POST = "USER_RECOVERPASSWORD_POST";
export const USER_RECOVERPASSWORD_SUCCESS = "USER_RECOVERPASSWORD_SUCCESS";
export const USER_RECOVERPASSWORD_FAILURE = "USER_RECOVERPASSWORD_FAILURE";
export const RESET_LOGIN = "RESET_LOGIN";
export const RESET_REGISTER = "RESET_REGISTER";
export const RESET_FORGOTPASSWORD = "RESET_FORGOTPASSWORD";
export const RESET_RECOVERPASSWORD = "RESET_RECOVERPASSWORD";
