/**
 * @author Calvin Galbaw
 */

export const PRODUCT_TOPRATING_GET = "PRODUCT_TOPRATING_GET";
export const PRODUCT_TOPRATING_SUCCESS = "PRODUCT_TOPRATING_SUCCESS";
export const PRODUCT_TOPRATING_ERROR = "PRODUCT_TOPRATING_ERROR";
export const PRODUCT_ALL_GET = "PRODDUCT_ALL_GET";
export const PRODUCT_ALL_SUCCESS = "PRODDUCT_ALL_SUCCESS";
export const PRODUCT_ALL_ERROR = "PRODDUCT_ALL_ERROR";
